services:
  db:
    image: mysql:8.0               
    environment:
      MYSQL_ROOT_PASSWORD: root        
      MYSQL_DATABASE: series            
    restart: always
    volumes :
      - ./backend/sql/local/:/docker-entrypoint-initdb.d
    ports:
      - "3307:3306"
  
  web_dragon:
    build: 
      context: frontend_dragon
      dockerfile: Dockerfile
    environment:
      API_BACKEND_URL: http://host.docker.internal:8080/api
    restart: always
    ports:
      - "8082:80"
    depends_on:
      - db

  web_stranger:
    build: 
      context: frontend_stranger
      dockerfile: Dockerfile
    environment:
      API_BACKEND_URL: http://host.docker.internal:8080/api 
    restart: always
    ports:
      - "8083:80"
    depends_on:
      - db
  
  phpmyadmin:
    image: phpmyadmin:latest
    container_name: admin
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: root
    ports:
      - "8084:80"
    depends_on:
      - db
